/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel_management;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author lohith
 */
public class NewJFrame9 extends javax.swing.JFrame {

    /** Creates new form NewJFrame9 */
    public NewJFrame9() {
        initComponents();
    }
    private static final String USERNAME = "root";
    private static final String PASSWORD = "Dushy12072001";
    private static final String CONN_STRING = "jdbc:mysql://localhost:3306/netbeans_hotel";
    int current;
    int max_row;
    ResultSet rs;
    
    int c=0;
    String n;
    int d = 0;
   
    int flag ;
    
    ResultSet cust(int c){
        try{
            Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            Statement st = connection.createStatement();
            String select = "select* from netbeans_hotel.current_customers;";
            rs = st.executeQuery(select);
            for(int i=0;i<c;i++){
            rs.next();}
        }catch(SQLException e){
            System.out.print(e);
        }
        return rs;
        
    }
    
    
    
   


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Current = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Registered = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Rooms = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        avail = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Rev = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Comp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CurrentPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RegisteredPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        AvailPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        RoomsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Revpanel = new javax.swing.JPanel();
        Comppanel = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));

        jPanel2.setPreferredSize(new java.awt.Dimension(194, 55));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Admin Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Current.setBackground(new java.awt.Color(128, 128, 128));
        Current.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurrentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CurrentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CurrentMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Customers");

        javax.swing.GroupLayout CurrentLayout = new javax.swing.GroupLayout(Current);
        Current.setLayout(CurrentLayout);
        CurrentLayout.setHorizontalGroup(
            CurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        CurrentLayout.setVerticalGroup(
            CurrentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        Registered.setBackground(new java.awt.Color(128, 128, 128));
        Registered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisteredMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisteredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisteredMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registerd Customers");

        javax.swing.GroupLayout RegisteredLayout = new javax.swing.GroupLayout(Registered);
        Registered.setLayout(RegisteredLayout);
        RegisteredLayout.setHorizontalGroup(
            RegisteredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisteredLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisteredLayout.setVerticalGroup(
            RegisteredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisteredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Rooms.setBackground(new java.awt.Color(128, 128, 128));
        Rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RoomsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RoomsMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rooms");

        avail.setBackground(new java.awt.Color(128, 128, 128));
        avail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                availMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                availMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Availability");

        javax.swing.GroupLayout availLayout = new javax.swing.GroupLayout(avail);
        avail.setLayout(availLayout);
        availLayout.setHorizontalGroup(
            availLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        availLayout.setVerticalGroup(
            availLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RoomsLayout = new javax.swing.GroupLayout(Rooms);
        Rooms.setLayout(RoomsLayout);
        RoomsLayout.setHorizontalGroup(
            RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RoomsLayout.setVerticalGroup(
            RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Rev.setBackground(new java.awt.Color(128, 128, 128));
        Rev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RevMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reviews");

        javax.swing.GroupLayout RevLayout = new javax.swing.GroupLayout(Rev);
        Rev.setLayout(RevLayout);
        RevLayout.setHorizontalGroup(
            RevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RevLayout.setVerticalGroup(
            RevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel10)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Comp.setBackground(new java.awt.Color(128, 128, 128));
        Comp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CompMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Complaints");

        javax.swing.GroupLayout CompLayout = new javax.swing.GroupLayout(Comp);
        Comp.setLayout(CompLayout);
        CompLayout.setHorizontalGroup(
            CompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CompLayout.setVerticalGroup(
            CompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Rooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(133, 133, 133))
            .addComponent(Rev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(Current, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Current, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Registered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(Rev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        CurrentPanel.setBackground(new java.awt.Color(192, 192, 192));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Room No");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton4.setText("Name");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton5.setText("Phone Number");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton6.setText("Option");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton7.setText("Check-In Date");

        jButton8.setText("Check-In Time");

        jButton10.setText("Room No");

        jButton11.setText("Fetch Data");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Previous");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Next");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton2.setText("Email");

        javax.swing.GroupLayout CurrentPanelLayout = new javax.swing.GroupLayout(CurrentPanel);
        CurrentPanel.setLayout(CurrentPanelLayout);
        CurrentPanelLayout.setHorizontalGroup(
            CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentPanelLayout.createSequentialGroup()
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurrentPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton12)
                        .addGap(41, 41, 41)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CurrentPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CurrentPanelLayout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11))
                            .addGroup(CurrentPanelLayout.createSequentialGroup()
                                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        CurrentPanelLayout.setVerticalGroup(
            CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(26, 26, 26)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(65, 65, 65)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(CurrentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.add(CurrentPanel, "card2");

        RegisteredPanel.setBackground(new java.awt.Color(192, 192, 192));

        jButton3.setText("Fetch Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton15.setText("Fetch Registered Email Address");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisteredPanelLayout = new javax.swing.GroupLayout(RegisteredPanel);
        RegisteredPanel.setLayout(RegisteredPanelLayout);
        RegisteredPanelLayout.setHorizontalGroup(
            RegisteredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisteredPanelLayout.createSequentialGroup()
                .addGroup(RegisteredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisteredPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton15))
                    .addGroup(RegisteredPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(RegisteredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegisteredPanelLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        RegisteredPanelLayout.setVerticalGroup(
            RegisteredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisteredPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(RegisteredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jPanel3.add(RegisteredPanel, "card3");

        AvailPanel.setBackground(new java.awt.Color(192, 192, 192));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Type", "Availability"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton9.setText("Fetch Data");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AvailPanelLayout = new javax.swing.GroupLayout(AvailPanel);
        AvailPanel.setLayout(AvailPanelLayout);
        AvailPanelLayout.setHorizontalGroup(
            AvailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvailPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(AvailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        AvailPanelLayout.setVerticalGroup(
            AvailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvailPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jPanel3.add(AvailPanel, "card4");

        RoomsPanel.setBackground(new java.awt.Color(192, 192, 192));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Availability"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Availability"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Availability"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Availability"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jButton14.setText("Fetch Data");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setText("Go Back");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoomsPanelLayout = new javax.swing.GroupLayout(RoomsPanel);
        RoomsPanel.setLayout(RoomsPanelLayout);
        RoomsPanelLayout.setHorizontalGroup(
            RoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(RoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RoomsPanelLayout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RoomsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        RoomsPanelLayout.setVerticalGroup(
            RoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(RoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(RoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton16))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel3.add(RoomsPanel, "card5");

        javax.swing.GroupLayout RevpanelLayout = new javax.swing.GroupLayout(Revpanel);
        Revpanel.setLayout(RevpanelLayout);
        RevpanelLayout.setHorizontalGroup(
            RevpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        RevpanelLayout.setVerticalGroup(
            RevpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(Revpanel, "card7");

        javax.swing.GroupLayout ComppanelLayout = new javax.swing.GroupLayout(Comppanel);
        Comppanel.setLayout(ComppanelLayout);
        ComppanelLayout.setHorizontalGroup(
            ComppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ComppanelLayout.setVerticalGroup(
            ComppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(Comppanel, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentMouseEntered
        // TODO add your handling code here:
        Current.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_CurrentMouseEntered

    private void CurrentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentMouseExited
        // TODO add your handling code here:
        Current.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_CurrentMouseExited

    private void RegisteredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisteredMouseEntered
        // TODO add your handling code here:
        Registered.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_RegisteredMouseEntered

    private void RegisteredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisteredMouseExited
        // TODO add your handling code here:
        Registered.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_RegisteredMouseExited

    private void availMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseEntered
        // TODO add your handling code here:
        avail.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_availMouseEntered

    private void availMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseExited
        // TODO add your handling code here:
        avail.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_availMouseExited

    private void RoomsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsMouseEntered
        // TODO add your handling code here:
        Rooms.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_RoomsMouseEntered

    private void RoomsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsMouseExited
        // TODO add your handling code here:
        Rooms.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_RoomsMouseExited

    private void RevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RevMouseEntered
        // TODO add your handling code here:
        Rev.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_RevMouseEntered

    private void RevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RevMouseExited
        // TODO add your handling code here:
        Rev.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_RevMouseExited

    private void CompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompMouseEntered
        // TODO add your handling code here:
        Comp.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_CompMouseEntered

    private void CompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompMouseExited
        // TODO add your handling code here:
        Comp.setBackground(new Color(128,128,128));
    }//GEN-LAST:event_CompMouseExited

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
            //Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            //Statement st = connection.createStatement();
            //String sql = "set SQL_SAFE_UPDATES = 0;";
            //st.execute(sql);
            //String select = "select *from  NetBeans_Hotel.current_customers ORDER BY room_no DESC LIMIT 1;";
            
            //rs = st.executeQuery(select);
            //rs.next();
            //max_row =rs.getInt("count");
            //System.out.print(max_row);
            //current = 1;
            //String select1 = "select* from NetBeans_Hotel.current_customers where count="+current+"";
            //rs = st.executeQuery(select1);
            
            rs = cust(1);
            c++;
            int Room = rs.getInt("room_no");
            String Room_no = String.valueOf(Room);
            String Email = rs.getString("email");
            String Name = rs.getString("name");
            String Phonenumber = rs.getString("phone_number");
            String Option = rs.getString("option_type");
            Date d = rs.getDate("checkin_date");
            DateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
            String cdate = dateFormat.format(d);
            Time t = rs.getTime("checkin_time");
            String strDateFormat = "HH:mm:ss a";
            SimpleDateFormat sdf = new SimpleDateFormat(strDateFormat);
            String ctime = sdf.format(t);
            jTextField3.setText(Room_no);
            jTextField4.setText(Email);
            jTextField5.setText(Name);
            jTextField6.setText(Phonenumber);
            jTextField7.setText(Option);
            jTextField8.setText(cdate);
            jTextField9.setText(ctime);
            jTextField2.setText(Room_no);
            
            
            
        }catch(SQLException e){
            System.out.print(e);
        }
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
        //if(current<max_row){
            //current = current+1;
            try{
            //Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            //Statement st = connection.createStatement();
            //String sql = "set SQL_SAFE_UPDATES = 0;";
            //st.execute(sql);
            
            c++;
            rs = cust(c);
            
            int Room = rs.getInt("room_no");
            String Room_no = String.valueOf(Room);
            String Email = rs.getString("email");
            String Name = rs.getString("name");
            String Phonenumber = rs.getString("phone_number");
            String Option = rs.getString("option_type");
            Date d = rs.getDate("checkin_date");
            DateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
            String cdate = dateFormat.format(d);
            Time t = rs.getTime("checkin_time");
            String strDateFormat = "HH:mm:ss a";
            SimpleDateFormat sdf = new SimpleDateFormat(strDateFormat);
            String ctime = sdf.format(t);
            jTextField3.setText(Room_no);
            jTextField4.setText(Email);
            jTextField5.setText(Name);
            jTextField6.setText(Phonenumber);
            jTextField7.setText(Option);
            jTextField8.setText(cdate);
            jTextField9.setText(ctime);
            jTextField2.setText(Room_no);
            
            
            
            
        }catch(SQLException e){
            System.out.print(e);
        }
        
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
        //if(current>1 && current<=max_row){
            //current = current-1;
            try{
            //Connection connection = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            //Statement st = connection.createStatement();
            //String sql = "set SQL_SAFE_UPDATES = 0;";
            //st.execute(sql);
            
            c--;
            rs = cust(c);
            
            int Room = rs.getInt("room_no");
            String Room_no = String.valueOf(Room);
            String Email = rs.getString("email");
            String Name = rs.getString("name");
            String Phonenumber = rs.getString("phone_number");
            String Option = rs.getString("option_type");
            Date d = rs.getDate("checkin_date");
            DateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
            String cdate = dateFormat.format(d);
            Time t = rs.getTime("checkin_time");
            String strDateFormat = "HH:mm:ss a";
            SimpleDateFormat sdf = new SimpleDateFormat(strDateFormat);
            String ctime = sdf.format(t);
            jTextField3.setText(Room_no);
            jTextField4.setText(Email);
            jTextField5.setText(Name);
            jTextField6.setText(Phonenumber);
            jTextField7.setText(Option);
            jTextField8.setText(cdate);
            jTextField9.setText(ctime);
            jTextField2.setText(Room_no);
            
            
        }catch(SQLException e){
            System.out.print(e);
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.setRowCount(0);
        try{
            Connection gaju = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            Statement govu = gaju.createStatement();
            String gajasam = "select* from netbeans_hotel.registered_users;";
            ResultSet gajan = govu.executeQuery(gajasam);
            while(gajan.next()){
                String mail = gajan.getString("email_address");
                String tbData[]={mail};
                tb1Model.addRow(tbData);
                
            }
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)jTable2.getModel();
        tb1Model.setRowCount(0);
        try{
            Connection ulta = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            Statement palta = ulta.createStatement();
            String silta = "Select* from netbeans_hotel.avail;";
            ResultSet q = palta.executeQuery(silta);
            while(q.next()){
                String r = q.getString("room_type");
                int a = q.getInt("availability");
                String aa =String.valueOf(a);
                String tbData[]={r,aa};
                tb1Model.addRow(tbData);
                
            }
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t1 = (DefaultTableModel)jTable3.getModel();
        t1.setRowCount(0);
        DefaultTableModel t2 = (DefaultTableModel)jTable4.getModel();
        t2.setRowCount(0);
        DefaultTableModel t3 = (DefaultTableModel)jTable5.getModel();
        t3.setRowCount(0);
        DefaultTableModel t4 = (DefaultTableModel)jTable6.getModel();
        t4.setRowCount(0);
        
        try{
            Connection lucky = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
            Statement lakshmi = lucky.createStatement();
            String selectlucky = "select* from netbeans_hotel.non_ac;";
            ResultSet la;
            la = lakshmi.executeQuery(selectlucky);
            while(la.next()){
                String R1 = la.getString("room_no");
                String A1 = la.getString("availability");
                String ta[] = {R1,A1};
                t1.addRow(ta);
            }
            String selectlucky1 = "select* from netbeans_hotel.semidelux;";
            la = lakshmi.executeQuery(selectlucky1);
            while(la.next()){
                String R1 = la.getString("room_no");
                String A1 = la.getString("availability");
                String tb[] = {R1,A1};
                t2.addRow(tb);
            }
            String selectlucky2 = "select* from netbeans_hotel.delux;";
            la = lakshmi.executeQuery(selectlucky2);
            while(la.next()){
                String R1 = la.getString("room_no");
                String A1 = la.getString("availability");
                String tc[] = {R1,A1};
                t3.addRow(tc);
            }
            String selectlucky3 = "select* from netbeans_hotel.private_suit;";
            la = lakshmi.executeQuery(selectlucky3);
            while(la.next()){
                String R1 = la.getString("room_no");
                String A1 = la.getString("availability");
                String td[] = {R1,A1};
                t4.addRow(td);
            }
            
            
            
            
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void CurrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentMouseClicked
        // TODO add your handling code here:
        CurrentPanel.setVisible(true);
        RegisteredPanel.setVisible(false);
        RoomsPanel.setVisible(false);
        Revpanel.setVisible(false);
        Comppanel.setVisible(false);
        AvailPanel.setVisible(false);
    }//GEN-LAST:event_CurrentMouseClicked

    private void RegisteredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisteredMouseClicked
        // TODO add your handling code here:
        CurrentPanel.setVisible(false);
        RegisteredPanel.setVisible(true);
        RoomsPanel.setVisible(false);
        Revpanel.setVisible(false);
        Comppanel.setVisible(false);
        AvailPanel.setVisible(false);
    }//GEN-LAST:event_RegisteredMouseClicked

    private void availMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseClicked
        // TODO add your handling code here:
        CurrentPanel.setVisible(false);
        RegisteredPanel.setVisible(false);
        RoomsPanel.setVisible(false);
        Revpanel.setVisible(false);
        Comppanel.setVisible(false);
        AvailPanel.setVisible(true);
    }//GEN-LAST:event_availMouseClicked

    private void RoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsMouseClicked
        // TODO add your handling code here:
        CurrentPanel.setVisible(false);
        RegisteredPanel.setVisible(false);
        RoomsPanel.setVisible(true);
        Revpanel.setVisible(false);
        Comppanel.setVisible(false);
        AvailPanel.setVisible(false);
    }//GEN-LAST:event_RoomsMouseClicked

    private void RevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RevMouseClicked
        // TODO add your handling code here:
        CurrentPanel.setVisible(false);
        RegisteredPanel.setVisible(false);
        RoomsPanel.setVisible(false);
        Revpanel.setVisible(true);
        Comppanel.setVisible(false);
        AvailPanel.setVisible(false);
    }//GEN-LAST:event_RevMouseClicked

    private void CompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompMouseClicked
        // TODO add your handling code here:
        CurrentPanel.setVisible(false);
        RegisteredPanel.setVisible(false);
        RoomsPanel.setVisible(false);
        Revpanel.setVisible(false);
        Comppanel.setVisible(true);
        AvailPanel.setVisible(false);
    }//GEN-LAST:event_CompMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AvailPanel;
    private javax.swing.JPanel Comp;
    private javax.swing.JPanel Comppanel;
    private javax.swing.JPanel Current;
    private javax.swing.JPanel CurrentPanel;
    private javax.swing.JPanel Registered;
    private javax.swing.JPanel RegisteredPanel;
    private javax.swing.JPanel Rev;
    private javax.swing.JPanel Revpanel;
    private javax.swing.JPanel Rooms;
    private javax.swing.JPanel RoomsPanel;
    private javax.swing.JPanel avail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
